name: keep-alive

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут (UTC)
  workflow_dispatch:         # можно запустить вручную из Actions

concurrency:
  group: keep-alive
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping health endpoints
        env:
          URLS: |
            https://vimly-16y2.onrender.com/healthz
            # можно добавить ещё строки с URL, по одному на строку
        run: |
          set -euo pipefail
          while IFS= read -r url; do
            [ -z "$url" ] && continue
            echo "→ $url"
            curl -A "keepalive-gha/1.0" \
                 -fsS --retry 3 --retry-delay 2 --retry-all-errors \
                 --max-time 10 -H "Cache-Control: no-cache" "$url" >/dev/null
          done <<< "$URLS"
          echo "✅ all good"
